<select name="week_name" class="form-control" required>
<option value="">--SELECT WEEK TO EDIT--</option>
<option value="one">Week One</option>
<option value="Two">Week Two</option>
<option value="Three">Week Three</option>
<option value="Four">Week Four</option>
<option value="Five">Week Five</option>
<option value="Six">Week Six</option>
<option value="Seven">Week Seven</option>
<option value="Eight">Week Eight</option>
<option value="Nine">Week Nine</option>
<option value="Ten">Week Ten</option>
<option value="Eleven">Week Eleven</option>
<option value="Twelve">Week Twelve</option>
<option value="Thirteen">Week Thirteen</option>
<option value="Fourteen">Week Fourteen</option>
<option value="Fifteen">Week Fifteen</option>
<option value="Sixteen">Week Sixteen</option>
<option value="Seventeen">Week Seventeen</option>
<option value="Eighteen">Week Eighteen</option>
<option value="Nineteen">Week Nineteen</option>
<option value="Twenty">Week Twenty</option>
<option value="TwentyOne">Week Twenty One</option>
<option value="TwentyTwo">Week Twenty Two</option>
<option value="TwentyThree">Week Twenty Three</option>
<option value="TwentyFour">Week TwentyFour</option>
<option value="TwentyFive">Week TwentyFive</option>
<option value="TwentySix">Week TwentySix</option>
<option value="TwentySeven">Week TwentySeven</option>
<option value="TwentyEight">Week TwentyEight</option>
<option value="TwentyNine">Week TwentyNine</option>
<option value="Thirty">Week Thirty</option>
<option value="ThirtyOne">Week ThirtyOne</option>
<option value="ThirtyTwo">Week ThirtyTwo</option>
<option value="ThirtyThree">Week ThirtyThree</option>
<option value="ThirtyFour">Week ThirtyFour</option>
<option value="ThirtyFive">Week ThirtyFive</option>
<option value="ThirtySix">Week ThirtySix</option>
<option value="ThirtySeven">Week ThirtySeven</option>
<option value="ThirtyEight">Week ThirtyEight</option>
<option value="ThirtyNine">Week ThirtyNine</option>
<option value="Fourty">Week Fourty</option>
<option value="FourtyOne">Week FourtyOne</option>
</select>